name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Start Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build production
        run: npm run build:prod
      - name: Linting
        run: npm run lint
      - name: Unit testing
        run: npm run test:unit
      - name: Build storybook
        run: npm run sb:build
      - name: Screenshot testing
        run: npm run test:ui:ci
